# Generated by Django 2.0.7 on 2019-01-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteurl',
            name='rateCount',
            field=models.IntegerField(default=0),
        ),
    ]
