# Generated by Django 2.0.7 on 2019-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollSite', '0002_siteurl_ratecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteurl',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
