# Generated by Django 2.0.7 on 2019-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollSite', '0003_siteurl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
