# Generated by Django 2.1.3 on 2019-04-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(default='', max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='question',
            name='etherSpent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_exp_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_exp_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_exp_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etherfeeds.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usrSig',
            field=models.CharField(default='0x0', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etherfeeds.Question'),
        ),
    ]
