# Generated by Django 2.1.3 on 2019-04-12 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0003_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 12, 49, 21, 395857), verbose_name='date expiring'),
        ),
    ]
