# Generated by Django 2.1.3 on 2019-04-12 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0004_question_exp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 13, 15, 14, 195590), verbose_name='date expiring'),
        ),
    ]
