# Generated by Django 2.1.3 on 2019-04-12 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0007_auto_20190412_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etherfeeds.Answer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='etherfeeds.Users')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 18, 4, 39, 276999), verbose_name='date expiring'),
        ),
    ]
