# Generated by Django 2.1.3 on 2019-04-14 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0009_auto_20190414_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='hashAns',
            field=models.CharField(default='0x0', max_length=200),
        ),
        migrations.AlterField(
            model_name='answerentries',
            name='hashAnsEnt',
            field=models.CharField(default='0x0', max_length=200),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 42, 25, 155494), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='hashMemProp',
            field=models.CharField(default='0x0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 42, 25, 154277), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='question',
            name='finalAns',
            field=models.CharField(default='0x0', max_length=200),
        ),
    ]
