# Generated by Django 2.1.3 on 2019-04-14 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0010_auto_20190414_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashlist',
            name='hash',
            field=models.CharField(default='0x0', max_length=200),
        ),
        migrations.AlterField(
            model_name='hashlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 46, 8, 453424), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 46, 8, 454942), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 46, 8, 454883), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 46, 8, 453723), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usrAddr',
            field=models.CharField(default='0x0', max_length=200),
        ),
    ]
