# Generated by Django 2.1.3 on 2019-04-14 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0011_auto_20190414_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberproposal',
            name='hashAnsEnt',
        ),
        migrations.AlterField(
            model_name='hashlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 47, 34, 35112), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 47, 34, 36593), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 47, 34, 36546), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 47, 34, 35409), verbose_name='date expiring'),
        ),
    ]
