# Generated by Django 2.1.3 on 2019-04-14 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0012_auto_20190414_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='hashAns',
        ),
        migrations.RemoveField(
            model_name='answerentries',
            name='hashAnsEnt',
        ),
        migrations.RemoveField(
            model_name='memberproposal',
            name='hashMemProp',
        ),
        migrations.AlterField(
            model_name='hashlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 49, 36, 169475), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 49, 36, 170930), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 12, 49, 36, 170883), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 12, 49, 36, 169778), verbose_name='date expiring'),
        ),
    ]
