# Generated by Django 2.1.3 on 2019-04-15 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherfeeds', '0017_auto_20190415_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerentries',
            name='claimed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hashlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 56, 5, 705874), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 12, 56, 5, 707486), verbose_name='date expiring'),
        ),
        migrations.AlterField(
            model_name='memberproposal',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 56, 5, 707432), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 12, 56, 5, 706181), verbose_name='date expiring'),
        ),
    ]
